"""ergmx: exponential-family random graph models (ERGMs) in Python, with a Rust core.

>>> import ergmx
>>> fit = ergmx.ergm(g, "edges + nodematch('Grade') + gwesp(0.5, fixed=TRUE)")  # doctest: +SKIP
>>> fit.summary()  # doctest: +SKIP
"""

from . import constraints, datasets
from ._compare import ModelComparison, compare
from ._diagnostics import McmcDiagnostics
from ._estimation import Control, DegeneracyError
from ._fit import ErgmFit, FitSummary
from ._gof import GofResult, GofTable, gof
from ._simulate import ergm, simulate, summary_stats
from .formula import FormulaError, parse_formula
from .terms import (
    ErgmDifferenceWarning,
    F,
    Formula,
    Term,
    absdiff,
    absdiffcat,
    asymmetric,
    b1concurrent,
    b1cov,
    b1degree,
    b1dsp,
    b1factor,
    b1nodematch,
    b1star,
    b2concurrent,
    b2cov,
    b2degree,
    b2dsp,
    b2factor,
    b2nodematch,
    b2star,
    concurrent,
    ctriple,
    cycle,
    degree,
    dsp,
    edgecov,
    edges,
    esp,
    gwb1degree,
    gwb1dsp,
    gwb2degree,
    gwb2dsp,
    gwdegree,
    gwdsp,
    gwesp,
    gwidegree,
    gwnsp,
    gwodegree,
    idegree,
    isolates,
    istar,
    kstar,
    mutual,
    nodecov,
    nodefactor,
    nodeicov,
    nodeifactor,
    nodematch,
    nodemix,
    nodeocov,
    nodeofactor,
    nsp,
    odegree,
    offset,
    ostar,
    receiver,
    sender,
    sociality,
    transitive,
    triangle,
    ttriple,
    twopath,
)

__version__ = "0.1.0.dev0"

__all__ = [
    "Control",
    "DegeneracyError",
    "ErgmDifferenceWarning",
    "ErgmFit",
    "F",
    "FitSummary",
    "Formula",
    "FormulaError",
    "GofResult",
    "GofTable",
    "McmcDiagnostics",
    "ModelComparison",
    "Term",
    "absdiff",
    "absdiffcat",
    "asymmetric",
    "b1concurrent",
    "b1cov",
    "b1degree",
    "b1dsp",
    "b1factor",
    "b1nodematch",
    "b1star",
    "b2concurrent",
    "b2cov",
    "b2degree",
    "b2dsp",
    "b2factor",
    "b2nodematch",
    "b2star",
    "compare",
    "concurrent",
    "constraints",
    "ctriple",
    "cycle",
    "datasets",
    "degree",
    "dsp",
    "edgecov",
    "edges",
    "ergm",
    "esp",
    "gof",
    "gwb1degree",
    "gwb1dsp",
    "gwb2degree",
    "gwb2dsp",
    "gwdegree",
    "gwdsp",
    "gwesp",
    "gwidegree",
    "gwnsp",
    "gwodegree",
    "idegree",
    "isolates",
    "istar",
    "kstar",
    "mutual",
    "nodecov",
    "nodefactor",
    "nodeicov",
    "nodeifactor",
    "nodematch",
    "nodemix",
    "nodeocov",
    "nodeofactor",
    "nsp",
    "odegree",
    "offset",
    "ostar",
    "parse_formula",
    "receiver",
    "sender",
    "simulate",
    "sociality",
    "summary_stats",
    "transitive",
    "triangle",
    "ttriple",
    "twopath",
]
